name: flutter_quill_delta_from_html
description: "Convert easily HTML inputs content to Quill Js Delta format"
version: 1.4.5
homepage:
repository: https://github.com/CatHood0/flutter_quill_delta_from_html
issue_tracker: https://github.com/CatHood0/flutter_quill_delta_from_html/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_quill_delta: ^10.0.0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
