name: flutter_quill_delta_from_html
description: "Convert easily HTML inputs content to Quill Delta format"
version: 1.1.7
homepage:
repository: https://github.com/CatHood0/flutter_quill_delta_from_html/
issue_tracker: https://github.com/CatHood0/flutter_quill_delta_from_html/issues

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill: ^9.5.7
  html: ^0.15.4
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
