name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Verify Flutter installation
        run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get
      
      - name: Run flutter_quill_delta_from_html tests
        run: flutter test

